blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: mailto:openscribbler.dev@pm.me
    about: For security vulnerabilities that could be actively exploited, please email us directly
